### ISSUE TITLE
innecesary connect mysql

### ISSUE THREAD

**Issue by juanpablocs** [ovr/phalcony#5]
the controller does not need mysql connection but connection requests.

Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [1049] Unknown database 'phalconxmodular'' in /Users/jpmaster/development/perured/phalconmodular/application/vendor/ovr/phalcony/src/Application.php:133

**Comment by ovr** [comment]
Hey! Sorry for the long delay, Can you show an example of usage?

**Comment by ovr** [comment]
Closed because no answer
